### PR TITLE
Add story for disabled form, fix bugs

### PR DESCRIPTION
**Pull request by gigxz**
## Description

* Add a DynamicForm story that has all input fields disabled. We can use this to reference that all inputs have correct styles and functionality when disabled
* Fix bug: SSN component wasn't fully disabled
* Fix bug: geolocation component wasn't fully disabled (could still clear)

Screenshot 2024-12-24 at 11 00 02 AM ==> Screenshot 2024-12-24 at 11 08 51 AM

## Type of change
- [x] Bug fix
- [x] Code clean-up / housekeeping

## Checklist before requesting review
- [x] I have performed a self-review of my code
- [x] I have run the code that is being changed under ideal conditions, and it doesn't fail
- [x] My code includes comments and/or descriptive variable names to help other engineers understand the intent (or not applicable)
- [x] My code follows the style guidelines of this project (eslint)
- [x] I have updated the documentation (or not applicable)
- [x] If it's not obvious how to test this change, I have provided testing instructions in this PR or the related issue

### CODE REVIEW

**Review by martha — APPROVED** [review]
Great, thank you!

It looks like file upload inputs are the last thing in the disabled form story that isn't disabled correctly, which I'm sure you saw. I don't think we have to fix it here, but it could be relatively straightforward to fix since `useDropzone` accepts a disabled prop. So, maybe it would be nice to fix here rather than making a separate ticket to track

Locally I tried out:
On `DynamicField`,
```
<Uploader
  ...
  disabled={commonInputProps.disabled}
/>
```

On `Uploader`:
add optional `disabled` prop and
```
useDropzone({
  ...
  disabled: disabled,
});
```
Then it's correctly disabled, but just needs some style/accessibility change to convey that it's disabled.

Again, fine with me if you want to fix this later!

**Comment by gigxz** [comment]
Thanks @martha I made those changes!

**Review by martha — APPROVED** [review]
sounds good thank you!

**Comment by gigxz** [comment]
Follow-up for styling issues: https://github.com/open-path/Green-River/issues/7141

**Pull request merged**
