### PR TITLE
makes nginx shut down more gracefully

### PR DESCRIPTION
**Pull request by yakloinsteak**

### CODE REVIEW

**Comment by yakloinsteak** [comment]
@gigxz Just wanted to make sure this was on your radar.

**Review by gigxz — APPROVED** [review]
Thanks Todd, sorry this slipped by me. It looks reasonable to me.

**Comment by gigxz** [comment]
Can I merge, or wait for Kyle's review?

**Comment by yakloinsteak** [comment]
Kyle and I talked about it, so go ahead and merge.

**Pull request merged**
