### PR TITLE
Minor storybook upgrade

### PR DESCRIPTION
**Pull request by gigxz**
## Description

Closes https://github.com/greenriver/hmis-frontend/pull/735

Minor upgrade only

## Type of change
- [x] Dependency update

## Checklist before requesting review
- [x] I have performed a self-review of my code
- [x] I have run the code that is being changed under ideal conditions, and it doesn't fail
- [ ] My code includes comments and/or descriptive variable names to help other engineers understand the intent (or not applicable)
- [ ] My code follows the style guidelines of this project (eslint)
- [ ] I have updated the documentation (or not applicable)
- [ ] If it's not obvious how to test this change, I have provided testing instructions in this PR or the related issue

### CODE REVIEW

**Review by ttoomey — APPROVED** [review]
This is probably fine. But I do worry a little about such a massive diff for a minor bump to storybook; there is some risk of creating dependency-related regressions.

Maybe we should check in on our approach to dependency management at some point

**Review by ttoomey — CHANGES_REQUESTED** [review]
Oh sorry I missed the build failures, changing approval status

**Comment by gigxz** [comment]
The diff is just because of the offline mirror,  we can definitely revisit that though. Not sure how reliable the registry is nowadays

**Comment by gigxz** [comment]
This was a really weird one, some packaged caused `Popper` types to change (not sure what) and I had to upgrade react types slightly to make it happy. I believe the underlying issue was https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/69006

**Review by ttoomey — APPROVED** [review]
Thanks for tracking down the build issue!

I was thinking that ideally bumping storybook up a minor version wouldn't require upgrading so many packages (~600). This might be because we are using yarn-deduplicate with the 'highest' strategy and it's causing churn. Or maybe it's that storybook just has massive dependencies. Something we can think about in the future, maybe we should move away from 'yarn classic' if it's too hard to mange

**Comment by gigxz** [comment]
Storybook definitely has massive dependencies, since it does transpilation it needs babel and everything (so those packages are not shared with prod, but they may be shared with jest which also transpiles).

Also I used upgrade-interactive so I wonder if that made it worse 👀

**Comment by gigxz** [comment]
But yeah def should revisit package manager tool at some point!

**Pull request merged**
