### PR TITLE
186801323 generate ce assessments from custom assessments

### PR DESCRIPTION
**Pull request by ttoomey**
## Description

[Support fully custom (non-HUD) assessments
](https://www.pivotaltracker.com/story/show/186494490)
[Support generating CE Assessments from Custom Assessments
](https://www.pivotaltracker.com/story/show/186801323)

[//]: # 'remove if not applicable'
[Depends on hmis-warehouse PR:](https://github.com/greenriver/hmis-warehouse/pull/3928)

## Type of change
[//]: # 'remove options that are not relevant'
- [x] New feature (adds functionality)

## Checklist before requesting review
- [x] I have performed a self-review of my code
- [x] I have run the code that is being changed under ideal conditions, and it doesn't fail
- [x] My code includes comments and/or descriptive variable names to help other engineers understand the intent (or not applicable)
- [x] My code follows the style guidelines of this project (eslint)
- [x] I have updated the documentation (or not applicable)
- [x] If it's not obvious how to test this change, I have provided testing instructions in this PR or the related issue

### CODE REVIEW

**Comment by gigxz** [comment]
Can we add the assessment name (definition title) into this column? It must just be based on the role currently. That may need to be updated both on the Client Dashboard and Enrollment Dashboard.
Screenshot 2024-01-23 at 12 16 53 PM

**Comment by gigxz** [comment]
I think these should also show the Definition Title

Screenshot 2024-01-23 at 3 42 42 PM

**Comment by gigxz** [comment]
It also looks like running codegen against the corresponding backend branch generates some changes @ttoomey

**Comment by ttoomey** [comment]
> It also looks like running codegen against the corresponding backend branch generates some changes @ttoomey

Thanks! Should be fixed, just a change to nullability on AssessmentRole rolled back

**Review by gigxz — CHANGES_REQUESTED** [review]
looks great I am excited!!  requested changes:
- show definition title in the assessment table on the enrollment dashboard (see commented screenshot)
- show definition title in the assessment table on the client dashboard (similar)
- show definition title in the assessment breadcrumb and page subtitle (see screenshot)  (there is a special function passed through context that lets you update breadcrumb title based on the page once its loaded 🙈 `overrideBreadcrumbTitles`

**Comment by ttoomey** [comment]
> * show definition title in the assessment table on the enrollment dashboard (see commented screenshot)
> * show definition title in the assessment table on the client dashboard (similar)
> * show definition title in the assessment breadcrumb and page subtitle (see screenshot)  (there is a special function passed through context that lets you update breadcrumb title based on the page once its loaded 🙈 `overrideBreadcrumbTitles`

I think these are all addressed in 9429b19fdddb7aea58cb9d016e0e1d708cd85e6b

**Review by gigxz — APPROVED** [review]

**Pull request merged**
